### ISSUE TITLE
Cannot finish creating config file with `earwigbot .earwigbot`

### ISSUE THREAD

**Issue by fhocutt** [earwig/earwigbot#63]
I am trying to install a local copy of copyvios for development work, and am following the directions in the README: https://github.com/earwig/copyvios

I am trying to create an earwigbot instance with `earwigbot .earwigbot` as directed. First it failed with: 
```python
EarwigBot v0.1

Config file missing or empty: /home/name/bots/copyvios/.earwigbot/config.yml
Would you like to create a config file now? [Y/n] y
I can't seem to write to the config file:
Traceback (most recent call last):
  File "/home/name/bots/copyvios/bin/earwigbot", line 9, in <module>
    load_entry_point('earwigbot==0.1', 'console_scripts', 'earwigbot')()
  File "/home/name/bots/copyvios/local/lib/python2.7/site-packages/earwigbot/util.py", line 134, in main
    bot = Bot(path.abspath(args.path), level=level)
  File "/home/name/bots/copyvios/local/lib/python2.7/site-packages/earwigbot/bot.py", line 74, in __init__
    self.config.load()
  File "/home/name/bots/copyvios/local/lib/python2.7/site-packages/earwigbot/config/__init__.py", line 267, in load
    self._handle_missing_config()
  File "/home/name/bots/copyvios/local/lib/python2.7/site-packages/earwigbot/config/__init__.py", line 117, in _handle_missing_config
    ConfigScript(self).make_new()
  File "/home/name/bots/copyvios/local/lib/python2.7/site-packages/earwigbot/config/script.py", line 422, in make_new
    open(self.config.path, "w").close()
IOError: [Errno 2] No such file or directory: '/home/name/bots/copyvios/.earwigbot/config.yml'
```
Manually creating a `.earwigbot/` directory solved this.

Now when I run `earwigbot .earwigbot`, attempting to configure for test.wikipedia.org, I to:
```
> Will this bot run on Wikimedia Foundation wikis, like Wikipedia?
[Y/n] y
> Site project (e.g. 'wikipedia', 'wiktionary', 'wikimedia'):
[wikipedia] wikipedia
> Site language code (e.g. 'en', 'fr', 'commons'): [en] test
> Bot username: BotUsername
> Bot password: <correct password>
Trying to connect to the site... API error!
API query failed: got error "assertuserfailed"; server says: "Assertion that the user is logged in failed".
> Would you like to re-enter the site information? [Y/n] 
```
If I do not re-enter the site information, it leaves an empty `.earwigbot/config.yml` file.

I expected:

1. to be able to create the config with an accurate user name and password for testwiki
2. if not, to be able to skip the field and continue creating the config file
3. if not, to be able to find an empty `config.yml` file that I could fill in manually.

**Comment by earwig** [comment]
You need to use the `develop` version, at least... the assertion issue is related to a change in MediaWiki that happened a while ago.

I will fix the first issue.

**Comment by fhocutt** [comment]
Great, thank you!

**Comment by fhocutt** [comment]
Worked great. Thanks again for such clear documentation.
